DUMMY_PASSWORD_HASH = "$argon2id$v=19$m=65536,t=3,p=4$ONyBRL6xJo7rHeyJC6Pwyw$Ygdi3NbnkmmDbd+hQ0gpw9krGw4OuXDhxXOQqHKKNn8"

MAX_SELECTOR_RETRIES = 3

REFRESH_COOKIE_NAME = "refresh_token"
REFRESH_COOKIE_PATH = "/auth"
