"""refactor project model

Revision ID: 26a07567b819
Revises: bc5177fc034c
Create Date: 2026-09-13 16:58:18.432941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26a07567b819'
down_revision: Union[str, None] = 'bc5177fc034c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slug', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index('ix_projects_deleted_at', 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index('ix_projects_user_deleted_at', 'projects', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.drop_column('projects', 'archived_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index('ix_projects_user_status', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index('ix_projects_user_deleted_at', table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index('ix_projects_deleted_at', table_name='projects')
    op.drop_column('projects', 'deleted_by')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'slug')
    # ### end Alembic commands ###
