"""update schema

Revision ID: 2d725d478189
Revises: 9466b3a5f8df
Create Date: 2026-08-18 16:21:36.542616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d725d478189'
down_revision: Union[str, None] = '9466b3a5f8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'estimated_duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
