"""create tasks and task_dependencies

Revision ID: 40b7b01e8076
Revises:
Create Date: 2026-07-25 22:24:11.819827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40b7b01e8076'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'CANCELLED', name='status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_enum'), nullable=False),
    sa.Column('type', sa.Enum('TASK', 'SUBTASK', 'EPIC', 'BUG', name='task_type_enum'), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.Enum('HUMAN', 'AGENT', name='created_by_enum'), nullable=False),
    sa.Column('approval_status', sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='approval_status_enum'), nullable=False),
    sa.Column('agent_permission_level', sa.Enum('PROPOSE_ONLY', 'ACT_FREELY', 'ACT_WITH_NOTIFY', name='agent_permission_level_enum'), nullable=True),
    sa.Column('agent_activity_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(3584), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.Enum('BLOCKS', 'BLOCKED_BY', 'RELATES_TO', name='dependency_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_table('tasks')
    # ### end Alembic commands ###
