"""refactor taskboard model

Revision ID: 443492c7e1f0
Revises: 26a07567b819
Create Date: 2026-09-13 17:15:16.677997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443492c7e1f0'
down_revision: Union[str, None] = '26a07567b819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskboard_tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_taskboard_tasks_task_id'), 'taskboard_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskboard_tasks_taskboard_id'), 'taskboard_tasks', ['taskboard_id'], unique=False)
    op.create_unique_constraint('uq_taskboard_tasks_position', 'taskboard_tasks', ['taskboard_id', 'position'], deferrable=True, initially='DEFERRED')
    op.add_column('taskboards', sa.Column('slug', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.add_column('taskboards', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('taskboards', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index('ix_taskboards_deleted_at', 'taskboards', ['deleted_at'], unique=False)
    op.create_index('ix_taskboards_project_deleted_at', 'taskboards', ['project_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_taskboards_project_id'), 'taskboards', ['project_id'], unique=False)
    op.create_index(op.f('ix_taskboards_slug'), 'taskboards', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskboards_slug'), table_name='taskboards')
    op.drop_index(op.f('ix_taskboards_project_id'), table_name='taskboards')
    op.drop_index('ix_taskboards_project_deleted_at', table_name='taskboards')
    op.drop_index('ix_taskboards_deleted_at', table_name='taskboards')
    op.drop_column('taskboards', 'deleted_by')
    op.drop_column('taskboards', 'deleted_at')
    op.drop_column('taskboards', 'slug')
    op.drop_constraint('uq_taskboard_tasks_position', 'taskboard_tasks', type_='unique')
    op.drop_index(op.f('ix_taskboard_tasks_taskboard_id'), table_name='taskboard_tasks')
    op.drop_index(op.f('ix_taskboard_tasks_task_id'), table_name='taskboard_tasks')
    op.drop_column('taskboard_tasks', 'updated_at')
    # ### end Alembic commands ###
