"""refactor action model

Revision ID: 44b9614dfb96
Revises: 92f77dc2d359
Create Date: 2026-09-13 17:44:41.391869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b9614dfb96'
down_revision: Union[str, None] = '92f77dc2d359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'plan',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_actions_project_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_user_id'), table_name='actions')
    op.create_index('ix_actions_expires_at', 'actions', ['expires_at'], unique=False)
    op.create_index('ix_actions_project_status_created', 'actions', ['project_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_actions_user_status_created', 'actions', ['user_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actions_user_status_created', table_name='actions')
    op.drop_index('ix_actions_project_status_created', table_name='actions')
    op.drop_index('ix_actions_expires_at', table_name='actions')
    op.create_index(op.f('ix_actions_user_id'), 'actions', ['user_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_index(op.f('ix_actions_project_id'), 'actions', ['project_id'], unique=False)
    op.alter_column('actions', 'plan',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
