"""rename field slug to public_id

Revision ID: 4d5af55c7cf6
Revises: 44b9614dfb96
Create Date: 2026-09-13 22:14:36.935020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5af55c7cf6'
down_revision: Union[str, None] = '44b9614dfb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.create_index(op.f('ix_projects_public_id'), 'projects', ['public_id'], unique=True)
    op.drop_column('projects', 'slug')
    op.add_column('taskboards', sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.drop_index(op.f('ix_taskboards_slug'), table_name='taskboards')
    op.create_index(op.f('ix_taskboards_public_id'), 'taskboards', ['public_id'], unique=True)
    op.drop_column('taskboards', 'slug')
    op.add_column('tasks', sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.drop_index(op.f('ix_tasks_slug'), table_name='tasks')
    op.create_index(op.f('ix_tasks_public_id'), 'tasks', ['public_id'], unique=True)
    op.drop_column('tasks', 'slug')
    op.add_column('users', sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.drop_column('users', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slug', sa.BIGINT(), sa.Identity(always=False, start=1000, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    op.drop_column('users', 'public_id')
    op.add_column('tasks', sa.Column('slug', sa.BIGINT(), sa.Identity(always=False, start=1000, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_tasks_public_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_slug'), 'tasks', ['slug'], unique=True)
    op.drop_column('tasks', 'public_id')
    op.add_column('taskboards', sa.Column('slug', sa.BIGINT(), sa.Identity(always=False, start=1000, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_taskboards_public_id'), table_name='taskboards')
    op.create_index(op.f('ix_taskboards_slug'), 'taskboards', ['slug'], unique=True)
    op.drop_column('taskboards', 'public_id')
    op.add_column('projects', sa.Column('slug', sa.BIGINT(), sa.Identity(always=False, start=1000, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_projects_public_id'), table_name='projects')
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.drop_column('projects', 'public_id')
    # ### end Alembic commands ###
