"""create all tables

Revision ID: 5c464cb7c515
Revises: 
Create Date: 2026-09-18 14:44:57.574859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c464cb7c515'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_project_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_at >= created_at', name='ck_users_deleted_after_created'),
    sa.CheckConstraint('length(username) >= 3', name='ck_users_username_min_length'),
    sa.ForeignKeyConstraint(['active_project_id'], ['projects.id'], name='fk_users_active_project_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_active_project_id', 'users', ['active_project_id'], unique=False)
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_is_active_deleted_at', 'users', ['is_active', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='project_status_enum'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('agent_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_agent_permission_level', sa.Enum('PROPOSE_ONLY', 'ACT_FREELY', 'ACT_WITH_NOTIFY', name='agent_permission_level_enum'), nullable=False),
    sa.Column('agent_activity_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_at >= created_at', name='ck_projects_deleted_after_created'),
    sa.CheckConstraint('start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= start_date', name='ck_projects_actual_end_after_start'),
    sa.CheckConstraint('start_date IS NULL OR target_end_date IS NULL OR target_end_date >= start_date', name='ck_projects_target_end_after_start'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_deleted_at', 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_public_id'), 'projects', ['public_id'], unique=True)
    op.create_index('ix_projects_user_deleted_at', 'projects', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('selector', sa.String(length=32), nullable=False),
    sa.Column('verifier_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('NOT (revoked_at IS NOT NULL AND replaced_by IS NOT NULL)', name='ck_revoked_xor_replaced'),
    sa.CheckConstraint('expires_at > created_at', name='ck_expires_after_created'),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_ip_address'), 'refresh_tokens', ['ip_address'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_selector'), 'refresh_tokens', ['selector'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_revoked_at', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('prompt', sa.String(length=10000), nullable=False),
    sa.Column('reply', sa.String(length=50000), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'confirmed') = (confirmed_at IS NOT NULL)", name='ck_actions_confirmed_state'),
    sa.CheckConstraint('expires_at > created_at', name='ck_actions_expires_after_created'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_actions_project_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_actions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actions_expires_at', 'actions', ['expires_at'], unique=False)
    op.create_index('ix_actions_project_status_created', 'actions', ['project_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_actions_user_status_created', 'actions', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('taskboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_at >= created_at', name='ck_taskboards_deleted_after_created'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_taskboards_deleted_at', 'taskboards', ['deleted_at'], unique=False)
    op.create_index('ix_taskboards_project_deleted_at', 'taskboards', ['project_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_taskboards_project_id'), 'taskboards', ['project_id'], unique=False)
    op.create_index(op.f('ix_taskboards_public_id'), 'taskboards', ['public_id'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'CANCELLED', name='status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_enum'), nullable=False),
    sa.Column('type', sa.Enum('TASK', 'SUBTASK', 'EPIC', 'BUG', name='task_type_enum'), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.Enum('HUMAN', 'AGENT', name='created_by_enum'), nullable=False),
    sa.Column('approval_status', sa.Enum('NONE', 'PENDING', 'APPROVED', 'REJECTED', name='approval_status_enum'), nullable=False),
    sa.Column('agent_permission_level', sa.Enum('PROPOSE_ONLY', 'ACT_FREELY', 'ACT_WITH_NOTIFY', name='agent_permission_level_enum'), nullable=True),
    sa.Column('agent_activity_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(2560), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("created_by <> 'AGENT' OR agent_permission_level IS NOT NULL", name='ck_tasks_agent_requires_permission_level'),
    sa.CheckConstraint("created_by <> 'AGENT' OR status <> 'DONE' OR approval_status = 'APPROVED'", name='ck_tasks_agent_completion_requires_approval'),
    sa.CheckConstraint('deleted_at IS NULL OR deleted_at >= created_at', name='ck_tasks_deleted_after_created'),
    sa.CheckConstraint('start_date IS NULL OR due_date IS NULL OR due_date > start_date', name='ck_tasks_due_after_start'),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_deleted_at', 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index('ix_tasks_project_deleted_at', 'tasks', ['project_id', 'deleted_at'], unique=False)
    op.create_index('ix_tasks_project_due_date', 'tasks', ['project_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_project_status_created_at', 'tasks', ['project_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_public_id'), 'tasks', ['public_id'], unique=True)
    op.create_table('task_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.Column('edge_type', sa.Enum('BLOCKS', 'BLOCKED_BY', 'RELATES_TO', name='edge_type_enum'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_id', name='ck_task_edges_no_self_reference'),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_id', 'edge_type', name='uq_task_edge')
    )
    op.create_index(op.f('ix_task_edges_depends_on_id'), 'task_edges', ['depends_on_id'], unique=False)
    op.create_index(op.f('ix_task_edges_public_id'), 'task_edges', ['public_id'], unique=True)
    op.create_index(op.f('ix_task_edges_task_id'), 'task_edges', ['task_id'], unique=False)
    op.create_table('taskboard_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taskboard_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_taskboard_tasks_position_non_negative'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taskboard_id'], ['taskboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taskboard_id', 'position', deferrable=True, initially='DEFERRED', name='uq_taskboard_tasks_position'),
    sa.UniqueConstraint('taskboard_id', 'task_id', name='uq_taskboard_task')
    )
    op.create_index(op.f('ix_taskboard_tasks_task_id'), 'taskboard_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskboard_tasks_taskboard_id'), 'taskboard_tasks', ['taskboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskboard_tasks_taskboard_id'), table_name='taskboard_tasks')
    op.drop_index(op.f('ix_taskboard_tasks_task_id'), table_name='taskboard_tasks')
    op.drop_table('taskboard_tasks')
    op.drop_index(op.f('ix_task_edges_task_id'), table_name='task_edges')
    op.drop_index(op.f('ix_task_edges_public_id'), table_name='task_edges')
    op.drop_index(op.f('ix_task_edges_depends_on_id'), table_name='task_edges')
    op.drop_table('task_edges')
    op.drop_index(op.f('ix_tasks_public_id'), table_name='tasks')
    op.drop_index('ix_tasks_project_status_created_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index('ix_tasks_project_due_date', table_name='tasks')
    op.drop_index('ix_tasks_project_deleted_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index('ix_tasks_deleted_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_taskboards_public_id'), table_name='taskboards')
    op.drop_index(op.f('ix_taskboards_project_id'), table_name='taskboards')
    op.drop_index('ix_taskboards_project_deleted_at', table_name='taskboards')
    op.drop_index('ix_taskboards_deleted_at', table_name='taskboards')
    op.drop_table('taskboards')
    op.drop_index('ix_actions_user_status_created', table_name='actions')
    op.drop_index('ix_actions_project_status_created', table_name='actions')
    op.drop_index('ix_actions_expires_at', table_name='actions')
    op.drop_table('actions')
    op.drop_index('ix_refresh_tokens_user_id_revoked_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_selector'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_ip_address'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_projects_user_status', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index('ix_projects_user_deleted_at', table_name='projects')
    op.drop_index(op.f('ix_projects_public_id'), table_name='projects')
    op.drop_index('ix_projects_deleted_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index('ix_users_is_active_deleted_at', table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_index('ix_users_active_project_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
