"""update embedding dim

Revision ID: 6eac9d5016b2
Revises: b65b5f8a6b21
Create Date: 2026-07-28 09:50:18.212564

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eac9d5016b2'
down_revision: Union[str, None] = 'b65b5f8a6b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'embedding')
    op.add_column('tasks', sa.Column('embedding', Vector(2560), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'embedding')
    op.add_column('tasks', sa.Column('embedding', Vector(3584), nullable=True))
    # ### end Alembic commands ###
