"""remove embedding column from project

Revision ID: 9466b3a5f8df
Revises: f477b0b7c5f5
Create Date: 2026-08-15 07:55:57.811099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9466b3a5f8df'
down_revision: Union[str, None] = 'f477b0b7c5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('embedding', Vector(2560), nullable=True))
    # ### end Alembic commands ###
