"""add public id to task dependency

Revision ID: acc798381cfa
Revises: 76cedb26afc9
Create Date: 2026-09-16 20:04:47.884758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc798381cfa'
down_revision: Union[str, None] = '76cedb26afc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_dependencies', sa.Column('public_id', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.create_index(op.f('ix_task_dependencies_public_id'), 'task_dependencies', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_public_id'), table_name='task_dependencies')
    op.drop_column('task_dependencies', 'public_id')
    # ### end Alembic commands ###
