"""refactor task model

Revision ID: bc5177fc034c
Revises: e10047c3bde8
Create Date: 2026-09-13 16:44:34.425533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5177fc034c'
down_revision: Union[str, None] = 'e10047c3bde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_dependencies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_task_dependencies_depends_on_id'), 'task_dependencies', ['depends_on_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_unique_constraint('uq_task_dependencies_edge', 'task_dependencies', ['task_id', 'depends_on_id', 'dependency_type'])
    op.add_column('tasks', sa.Column('slug', sa.BigInteger(), sa.Identity(always=False, start=1000, increment=1), nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_index('ix_tasks_deleted_at', 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index('ix_tasks_project_deleted_at', 'tasks', ['project_id', 'deleted_at'], unique=False)
    op.create_index('ix_tasks_project_due_date', 'tasks', ['project_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_project_status_created_at', 'tasks', ['project_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_slug'), 'tasks', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_slug'), table_name='tasks')
    op.drop_index('ix_tasks_project_status_created_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index('ix_tasks_project_due_date', table_name='tasks')
    op.drop_index('ix_tasks_project_deleted_at', table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_index('ix_tasks_deleted_at', table_name='tasks')
    op.drop_column('tasks', 'deleted_by')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'slug')
    op.drop_constraint('uq_task_dependencies_edge', 'task_dependencies', type_='unique')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_depends_on_id'), table_name='task_dependencies')
    op.drop_column('task_dependencies', 'created_at')
    # ### end Alembic commands ###
