"""add user model and update others

Revision ID: ccac149a5b17
Revises: df5ae437804f
Create Date: 2026-08-27 21:03:24.681639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccac149a5b17'
down_revision: Union[str, None] = 'df5ae437804f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active_project_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['active_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('actions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_actions_user_id'), 'actions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('tasks_parent_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_parent_id_fkey'), 'tasks', 'tasks', ['parent_id'], ['id'])
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_index(op.f('ix_actions_user_id'), table_name='actions')
    op.drop_column('actions', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
