"""make project id non nullable

Revision ID: df5ae437804f
Revises: 94ff910e53ca
Create Date: 2026-08-26 15:54:20.987104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5ae437804f'
down_revision: Union[str, None] = '94ff910e53ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskboards', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('taskboards_project_id_fkey'), 'taskboards', type_='foreignkey')
    op.create_foreign_key(None, 'taskboards', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskboards', type_='foreignkey')
    op.create_foreign_key(op.f('taskboards_project_id_fkey'), 'taskboards', 'projects', ['project_id'], ['id'])
    op.alter_column('taskboards', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
