"""add constraints

Revision ID: eedad55a8add
Revises: 4d5af55c7cf6
Create Date: 2026-09-13 22:21:49.882038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedad55a8add'
down_revision: Union[str, None] = '4d5af55c7cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_actions_confirmed_state', 'actions', "(status = 'confirmed') = (confirmed_at IS NOT NULL)")
    op.create_check_constraint('ck_actions_expires_after_created', 'actions', 'expires_at > created_at')
    op.create_check_constraint('ck_projects_actual_end_after_start', 'projects', 'start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= start_date')
    op.create_check_constraint('ck_projects_deleted_after_created', 'projects', 'deleted_at IS NULL OR deleted_at >= created_at')
    op.create_check_constraint('ck_projects_target_end_after_start', 'projects', 'start_date IS NULL OR target_end_date IS NULL OR target_end_date >= start_date')
    op.create_check_constraint('ck_task_dependencies_no_self_reference', 'task_dependencies', 'task_id <> depends_on_id')
    op.create_check_constraint('ck_taskboard_tasks_position_non_negative', 'taskboard_tasks', 'position >= 0')
    op.create_check_constraint('ck_taskboards_deleted_after_created', 'taskboards', 'deleted_at IS NULL OR deleted_at >= created_at')
    op.create_check_constraint('ck_tasks_agent_completion_requires_approval', 'tasks', "created_by <> 'agent' OR status <> 'done' OR approval_status = 'approved'")
    op.create_check_constraint('ck_tasks_agent_requires_permission_level', 'tasks', "created_by <> 'agent' OR agent_permission_level IS NOT NULL")
    op.create_check_constraint('ck_tasks_deleted_after_created', 'tasks', 'deleted_at IS NULL OR deleted_at >= created_at')
    op.create_check_constraint('ck_tasks_due_after_start', 'tasks', 'start_date IS NULL OR due_date IS NULL OR due_date > start_date')
    op.create_check_constraint('ck_users_deleted_after_created', 'users', 'deleted_at IS NULL OR deleted_at >= created_at')
    op.create_check_constraint('ck_users_username_min_length', 'users', 'length(username) >= 3')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_username_min_length', 'users', type_='check')
    op.drop_constraint('ck_users_deleted_after_created', 'users', type_='check')
    op.drop_constraint('ck_tasks_due_after_start', 'tasks', type_='check')
    op.drop_constraint('ck_tasks_deleted_after_created', 'tasks', type_='check')
    op.drop_constraint('ck_tasks_agent_requires_permission_level', 'tasks', type_='check')
    op.drop_constraint('ck_tasks_agent_completion_requires_approval', 'tasks', type_='check')
    op.drop_constraint('ck_taskboards_deleted_after_created', 'taskboards', type_='check')
    op.drop_constraint('ck_taskboard_tasks_position_non_negative', 'taskboard_tasks', type_='check')
    op.drop_constraint('ck_task_dependencies_no_self_reference', 'task_dependencies', type_='check')
    op.drop_constraint('ck_projects_target_end_after_start', 'projects', type_='check')
    op.drop_constraint('ck_projects_deleted_after_created', 'projects', type_='check')
    op.drop_constraint('ck_projects_actual_end_after_start', 'projects', type_='check')
    op.drop_constraint('ck_actions_expires_after_created', 'actions', type_='check')
    op.drop_constraint('ck_actions_confirmed_state', 'actions', type_='check')
    # ### end Alembic commands ###
