"""add embedding to project

Revision ID: f477b0b7c5f5
Revises: a80dad077a82
Create Date: 2026-07-30 21:30:23.359378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'f477b0b7c5f5'
down_revision: Union[str, None] = 'a80dad077a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('embedding', Vector(2560), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'embedding')
    # ### end Alembic commands ###
